### ISSUE TITLE
Flashing transition between images

### ISSUE THREAD

**Issue by kingstonheath** [blynkkk/beta#165]
I have seen an issue raised relating to jerky video so not sure whether this is related.  I am using a series of static images with short delays between (2 secs) to simulate a door opening.  In Blynk V1, the transition was very smooth.  In Blynk V2, the image flashes between each transition (ie a short period where no image is displayed).

**Comment by doom369** [comment]
@kingstonheath hello is that android or ios or both?

**Comment by kingstonheath** [comment]
Apologies - android

**Comment by alexkipar** [comment]
@kingstonheath why not use the image gallery widget and change its value to switch between images list? 

If this is a video stream - we are switching to another more stable video streaming support, not sure we can somehow change this behavior. Can you provide details about your video stream: which format is used? RTSP or not? Motion JPEG inside or what?

**Comment by kingstonheath** [comment]
Thanks for your response.  This is not a video.  I am using the image gallery widget.  I don't understand you comment "why not use the image gallery widget and change its value to switch between images list?"  Where is this value?

Steve

**Comment by alexkipar** [comment]
@kingstonheath I thought the comment about jerky video was about showing images via motion jpeg in video widget. Ok, got the issue. Next week will be a new build so I think it will contain a fix to this issue.

**Comment by hms-11** [comment]
Hello @alexkipar  I have a similar issue involving a program that previously worked on "old" Blynk but now has this issue, among others in Blynk2.0. 

Should I create a new issue with details or explain my problem in here? When is the new build being released? If it contains the fix this will be a non issue for me.

**Comment by hms-11** [comment]
@alexkipar I've got a workaround, if not an outright fix.
Blynk.setProperty seems to be far more responsive/sensitive in Blynk2.0 in comparison to the old one.
I had issues with flickering when the program was running a set property command as a regularly occuring function but when I added a boolean flag to check if the pointed URL was changed or not and only ran Blynk.setProperty if there was an updated URL it resolved my flickering issue. 

I'm having issues forcing it to flush the cache but that is a whole other issue so I'll open a new ticket. 

Pseudo code to fix flickering:
```
  if (newImage) {
  Blynk.setProperty(V0, "url", 1, coopImageURL);
  Blynk.virtualWrite(V0, 1);
  newImage = false;       
}
``` 
newImage is set true elsewhere in the code but this ensures there isn't constant Blynk.setProperty commands being sent.

**Comment by alexkipar** [comment]
@hms-11 I suppose the next build will fix this issue; I hope it will be ready on Tuesday or Friday, depending on the Play Store review duration. First, I'll check the cache clearing code; it should clear the cache when the set property call has been used.

**Comment by hms-11** [comment]
@alexkipar 
Yeah the cache clearing is an issue I had with "old" Blynk as well, so it could potentially be sloppy coding on my part.
Basically, I have a program where an ESP32CAM takes a photo, and uploads it to an FTP server to be available for the Blynk Image Gallery Widget. To keep folder sizes down, my original plan was to simply overwrite the image each time, and use set property to flush the cache and grab the new image. However, since they share the same URL, the cache wouldn't clear as it didn't see it as a "new" image. My fix was to have a set of 3 image names it rotates through. So first time a photo is requested, it takes a photo and uploads it as "CoopPic1", the next photo is uploaded as "CoopPic2" and then finally "CoopPic3". After that it circles back to "CoopPic1" and overwrites that image. Virtual Write is then used to point the Image Gallery Widget to the appropriate picture (V0, 1 or 2) and setProperty is used to flush the cache. In "old" Blynk this was sufficient to force a cache change and supply a new image but Blynk2.0 seems to still hang on the cache.

**Comment by alexkipar** [comment]
@hms-11, can you send logs from the app (the about screen - send logs) - old blynk and the new one uses the same code for cache clearing; maybe it is another issue.

**Comment by hms-11** [comment]
@alexkipar, I think my code may in fact have been the problem and that I was just getting lucky with old Blynk. I have a working solution now that seems to function very well, no flickering, successful cache clearing and all seems well. Originally (old Blynk) my program was rearranging the image order in the app with the setProperty function which worked with my code but would sometimes cause random image hangs I could never explain. I now just leave the app image index as-is and assign my pointers better in code.
```
// Changes image in Blynk app depending on camera state
void loadingImage( void ) {
if (loading) { 
  Blynk.virtualWrite(V0, (i+2));
  if (i <= 9) {
    i ++;
  }
  else if (i > 9) {
    i = 1;
  }
}
else if (!loading) {
  if (ic == 1) {
    coopImageURL = "https://coopcommandimages.000webhostapp.com/uploads/coopPic5.jpg";
  }
  else if (ic == 2) {
    coopImageURL = "https://coopcommandimages.000webhostapp.com/uploads/coopPic6.jpg";
  }
  else if (ic == 3) {
    coopImageURL = "https://coopcommandimages.000webhostapp.com/uploads/coopPic7.jpg";
  }
  if (newImage) {
  Blynk.setProperty(V0, "url", (ic-1), coopImageURL);
  Blynk.virtualWrite(V0, (ic-1));
  newImage = false;       
}
i = 1; 
}
}
```

This is working well for me for my purposes. I can include my entire code if you like and I can still include logs if you want but I do believe the problem was me haha. 

Thanks for the help with this issue.

**Comment by alexkipar** [comment]
@hms-11, please check the 1.1.9 app's version; if it does not fix the issue - please resend apps logs

**Comment by hms-11** [comment]
@alexkipar issue is resolved in my testing. Thanks for the fix!
