### ISSUE TITLE
pin selection, groups and automation missing from app

### ISSUE THREAD

**Issue by spiutm** [blynkkk/beta#6]
pin selection, groups and automation missing from app

**Comment by Peterkn2001** [comment]
Pin selection is done via Datastreams. These have to be defined in the web dashboard and are done at Template level.

Pete.

**Comment by doom369** [comment]
@spiutm Peter is right.

**DataStreams**

Now you have to assign a datastream instead of the pin. Datastream is a part of the Template on the Web Dashboard. At the moment there is no editor of the template on the mobile. So you have to create it on the web.

**groups**

Groups are disabled for the Beta. We plan to refactor them soon. So we decided to hide them for now.

**automation**

In order to enable automation, you have to create a DataStream that is enabled for the  automation:
![screenshot-dash-qa blynk cc-2021 03 27-11_12_41](https://user-images.githubusercontent.com/1536494/112716165-67838d00-8eed-11eb-9608-28bcb09f86f4.png)

**Comment by Peterkn2001** [comment]
It seems that the only automation actions are "send email" or "send notification".
Does this mean that it's not possible to update the value of another widget via an automation?

Pete.

**Comment by doom369** [comment]
@Peterkn2001 do you have the datastreams with "Avaialble in Actions" checkbox checked?

**Comment by Peterkn2001** [comment]
Yes, and LED widget attached to V0, that I was trying to control with a button widget attached to V1.
This is the LED widget setup...
![image](https://user-images.githubusercontent.com/35718564/112716646-76634300-8edf-11eb-9b8b-e04f5004bbe9.png)

Pete.

**Comment by doom369** [comment]
@Peterkn2001 could you please clarify: you don't see the option "Set device to" in the actions list or you don't see any device after you have selected the "Set device to" action?

**Comment by doom369** [comment]
@Peterkn2001 I checked the logs, seems like app issue. I created a separate issue for that - https://github.com/blynkkk/beta/issues/9. Could you please send app logs it will help.

**Comment by Peterkn2001** [comment]
Done, although my log file doesn't seem to show very much.

Pete.

**Comment by spiutm** [comment]
so now all pins are just virtual? you have to connect virtual pin to analog pin in sketch? isn't that a downgrade from old blynk?

**Comment by doom369** [comment]
> so now all pins are just virtual?

For now - yes.

> isn't that a downgrade from old blynk?

From the point of view of "wow" effect it is. From the point of view of "real" hardware products - it's not. We have 0 customers who need this.

**Comment by spiutm** [comment]
sad, more code, less memory, the logic here behind virtual pins is that u can control more then 1 analog pins in same time with just 1 virtual pin, but that has a bad application over individual sensors, multi pwm cases, etc

**Comment by doom369** [comment]
It's not something we won't do. It's just not yet done on the new platform. It's in our plans.
