### ISSUE TITLE
I can't find the About of the web dashboard

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#97]
I can't find the About in the web dashboard.

**Comment by doom369** [comment]
@whogarden could you please clarify what do you mean by "About"?

**Comment by whogarden** [comment]
I just need to know the "Version" of the https://blynk.cloud/dashboard/xxx

**Comment by whogarden** [comment]
For example,
I have problems with the chart size, and I am asking me if it's a mishandling or if it because there is a new web version.

**Comment by whogarden** [comment]
For example,
I have problems with the chart size, and I am asking me if it's a mishandling or if it is because there is a new web version.

**Comment by doom369** [comment]
I see... Yes, this is good point. We'll think about it.

**Comment by doom369** [comment]
@whogarden hello. After thinking a while we decided not to add this. This is because the web version is always the latest one. The only way to get a non-latest web version would be to have a browser cache. However, during the page refresh the index page should always be refreshed. So the only way to get the not latest web page is to have an open page that is never refreshed. That is not a case in the real use cases.
